name: Test

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: yarn --immutable
    - run: yarn runty lint
    - run: yarn runty build
    - run: yarn runty test
      env:
        CI: true
